import{a as v,i as m,S as B}from"./assets/vendor-53a1b719.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();const L="44952732-afe4551e0894d66c0b6ee4476";async function f(s,r=1,n=15){const a=`https://pixabay.com/api/?key=${L}&q=${s}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${n}`;try{return(await v.get(a)).data}catch(t){throw new Error(t.response.status)}}function S(){m.show({message:"Sorry, there are no images matching your search query. Please try again!",class:"toast-style",messageColor:"white",titleColor:"white",iconColor:"white"})}function g(){m.info({title:"Info",message:"No images found.",class:"toast-style",messageColor:"white",titleColor:"white",iconColor:"white"})}function y({webformatURL:s,largeImageURL:r,tags:n,likes:a,views:t,comments:o,downloads:i}){return`
  <div class ="image-container">
    <a href="${r}" class = "image-link">

    <li class="image-item">
      <img src="${s}" alt="${n}" />
    </li>
    <div class ="">
      <li class="image-item-info">
        <p><span class = "comment-head">Likes</span> ${a}</p>
        <p><span class = "comment-head">Views</span> ${t}</p>
        <p><span class = "comment-head">Comments</span> ${o}</p>
        <p><span class = "comment-head">Downloads</span> ${i}</p>
      </li>
    </div>
    </a>
  </div>
  `}function h(){m.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})}const e={submitBtn:document.querySelector(".js-submit-btn"),form:document.querySelector("form[data-form]"),input:document.querySelector("input[data-input]"),gallery:document.querySelector(".gallery"),loading:document.querySelector(".loadingText"),loadMoreBtn:document.querySelector(".js-loadmore-btn")},b=new B(".image-link",{captions:!0,captionSelector:"img",captionsData:"alt",captionType:"attr",captionPosition:"bottom",captionDelay:250});let l=1;const w=15;let d="",u=0,c=0;async function $(s){s.preventDefault(),e.loadMoreBtn.style.display="none";const r=e.input.value.trim(),n=e.input.value;d!==r&&(l=1,d=r,c=0);function a(){return r===""?(e.submitBtn.disabled=!0,S(),!0):(e.submitBtn.disabled=!1,!1)}function t(o){const i=o.hits;let p="";i.forEach(M=>{p+=y(M)}),e.gallery.innerHTML=p,b.refresh(),c+=i.length,c>=u?(e.loadMoreBtn.style.display="none",h()):e.loadMoreBtn.style.display="flex",I()}if(e.gallery.innerHTML="",e.form.reset(),a()){e.submitBtn.disabled=!1;return}e.loading.style.display="block";try{const o=await f(n,l,w);u=o.totalHits,setTimeout(()=>{if(e.loading.style.display="none",o.hits.length===0){g();return}t(o),e.gallery.style.display="flex",l+=1},1e3)}catch{e.loading.style.display="none",iziToast.error({title:"Error",message:"No Images found or an error occurred while fetching images."})}}async function q(){e.loading.style.display="block";try{const s=await f(d,l,w);setTimeout(()=>{if(e.loading.style.display="none",s.hits.length===0){g();return}const r=s.hits;let n="";r.forEach(a=>{n+=y(a)}),e.gallery.insertAdjacentHTML("beforeend",n),b.refresh(),c+=r.length,c>=u?(e.loadMoreBtn.style.display="none",h()):e.loadMoreBtn.style.display="flex",I(),l+=1},1e3)}catch{e.loading.style.display="none",iziToast.error({title:"Error",message:"No Images found or an error occurred while fetching images."})}}function I(){const s=document.querySelector(".gallery .photo-card");if(s){const r=s.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}}e.form.addEventListener("submit",$);e.loadMoreBtn.addEventListener("click",q);
//# sourceMappingURL=commonHelpers.js.map
